services:

  mariadb:
      build:
          context: requirements/MariaDB

      container_name: mariadb

      env_file:
          - .env

      volumes:
          - mariadb_volume:/var/lib/mysql

      networks:
          - inception

      restart: always

  wordpress:
      build:
          context: requirements/WordPress

      container_name: wordpress

      env_file:
          - .env

      volumes:
          - wordpress_volume:/var/www/html

      networks:
          - inception
          
      depends_on:
          - mariadb

      restart: always


volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/${LOGIN}/data/mariadb
      o: bind

  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/${LOGIN}/data/wordpress
      o: bind

networks:
  inception: